// Package docs — stub generated by swaggo/swag. Run `make swagger` to regenerate.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "LIFE API",
        "description": "API for the LIFE application",
        "version": "1.0"
    },
    "basePath": "/v1",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "LIFE API",
	Description:      "API for the LIFE application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
